"""empty message

Revision ID: ed40128fdb36
Revises: 4558e4486ba1
Create Date: 2018-04-10 12:16:15.494744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed40128fdb36'
down_revision = '4558e4486ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('user', sa.Column('street', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('zip', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'street')
    op.drop_column('user', 'state')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
